# Generated by Django 6.0.3 on 2026-04-07 07:39

import django.db.models.deletion
import license_server.licensing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LicenseKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, help_text='Optional name of the software', max_length=100, null=True)),
                ('reference_id', models.CharField(default=license_server.licensing.models.generate_reference_id, max_length=25, unique=True)),
                ('key', models.TextField(help_text='The encrypted offline token payload', unique=True)),
                ('duration_days', models.IntegerField(default=10, help_text='Duration in days')),
                ('is_active', models.BooleanField(default=True)),
                ('grace_period_days', models.IntegerField(default=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='licensing.clientprofile')),
            ],
        ),
    ]
